[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20.16.0"


[[headers]]
  for = "/*"
  [headers.values]
   Content-Security-Policy = "frame-ancestors 'self' https://storenotify.in http://localhost:4200 https://atmdemoaivenmysql.onrender.com https://rzp.io"
     X-XSS-Protection = "1; mode=block"
    X-Robots-Tag = "index"
    Cache-Control = "public, max-age=0, no-cache, no-store, must-revalidate"


[[headers]]
for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://storenotify.in, https://sheer-maryjo-storenotify-4c573750.koyeb.app, http://localhost:4200, http://localhost:3450, http://localhost:8888, https://storenotiftycom.netlify.app, https://atmdemoaivenmysql.onrender.com, https://rzp.io"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Credentials = "true"
